.TH "/home/pedro/Dropbox/UnB2017-1/Introdução ao Processamento de Imagens/Projetos/Trabalhos/Trab1IPI/Ex2/src Directory Reference" 3 "Mon May 8 2017" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/pedro/Dropbox/UnB2017-1/Introdução ao Processamento de Imagens/Projetos/Trabalhos/Trab1IPI/Ex2/src Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBrealces\&.cc\fP"
.br
.RI "\fIArquivo que contém os filtros de realce do contraste de imagens\&. \fP"
.ti -1c
.RI "file \fBtrabalho\&.cc\fP"
.br
.RI "\fIArquivo do segundo exercício do primeiro trabalho de IPI UnB - 1/2017\&. \fP"
.in -1c
