.TH "/home/pedro/Dropbox/UnB2017-1/Introdução ao Processamento de Imagens/Projetos/Trabalhos/Trab1IPI/Ex1/include Directory Reference" 3 "Mon May 8 2017" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/pedro/Dropbox/UnB2017-1/Introdução ao Processamento de Imagens/Projetos/Trabalhos/Trab1IPI/Ex1/include Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBdec_int\&.h\fP"
.br
.RI "\fIArquivo que contém a biblioteca de \fBdec_int\&.cc\fP\&. \fP"
.in -1c
