.TH "/home/pedro/Dropbox/UnB2017-1/Introdução ao Processamento de Imagens/Projetos/Trabalhos/Trab1IPI/Ex1/src Directory Reference" 3 "Mon May 8 2017" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/pedro/Dropbox/UnB2017-1/Introdução ao Processamento de Imagens/Projetos/Trabalhos/Trab1IPI/Ex1/src Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBdec_int\&.cc\fP"
.br
.RI "\fIArquivo que expande os pixels de uma imagem\&. \fP"
.ti -1c
.RI "file \fBedge_improv\&.cc\fP"
.br
.RI "\fIArquivo que contém os filtros de melhoramento subjetivo de imagens e que os aplica\&. \fP"
.ti -1c
.RI "file \fBtrabalho\&.cc\fP"
.br
.RI "\fIArquivo do primeiro exercício do primeiro trabalho de IPI UnB - 1/2017\&. \fP"
.in -1c
