.TH "/home/pedro/Dropbox/UnB2017-1/Introdução ao Processamento de Imagens/Projetos/Trabalhos/Trab1IPI/Ex1/src/dec_int.cc" 3 "Mon May 8 2017" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/pedro/Dropbox/UnB2017-1/Introdução ao Processamento de Imagens/Projetos/Trabalhos/Trab1IPI/Ex1/src/dec_int.cc \- Arquivo que expande os pixels de uma imagem\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <dec_int\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBdec_int\fP (char *img_entrada, int fator)"
.br
.RI "\fIQuadriculador de imagens\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Arquivo que expande os pixels de uma imagem\&. 


.PP
\fBAuthor:\fP
.RS 4
Pedro Nogueira - 14/0065032 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "void dec_int (char * img_entrada, int fator)"

.PP
Quadriculador de imagens\&. Multiplica as dimensões de cada pixel de uma imagem por um fator\&.
.PP
\fBParameters:\fP
.RS 4
\fIimg_entrada\fP - Imagem a ser expandida 
.br
\fIfator\fP - Fator usado para multiplicar as dimensões dos pixels 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
