.TH "/home/pedro/Dropbox/UnB2017-1/Introdução ao Processamento de Imagens/Projetos/Trabalhos/Trab1IPI/Ex1/src/edge_improv.cc" 3 "Mon May 8 2017" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/pedro/Dropbox/UnB2017-1/Introdução ao Processamento de Imagens/Projetos/Trabalhos/Trab1IPI/Ex1/src/edge_improv.cc \- Arquivo que contém os filtros de melhoramento subjetivo de imagens e que os aplica\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <edge_improv\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBedge_improv\fP (char *img_entrada)"
.br
.RI "\fIInterface para o usuário ter acesso às ferramentas de melhoria subjetiva de uma imagem\&. \fP"
.ti -1c
.RI "Mat \fBfiltro_custom\fP (Mat img, int fator)"
.br
.RI "\fIFiltro de média\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Arquivo que contém os filtros de melhoramento subjetivo de imagens e que os aplica\&. 


.PP
\fBAuthor:\fP
.RS 4
Pedro Nogueira - 14/0065032 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "void edge_improv (char * img_entrada)"

.PP
Interface para o usuário ter acesso às ferramentas de melhoria subjetiva de uma imagem\&. Somente contém as opções de filtros que o usuário pode utilizar na imagem\&. Sujeito a expansão\&.
.PP
\fBParameters:\fP
.RS 4
\fIimg_entrada\fP - Imagem a ser manipulada 
.RE
.PP

.SS "Mat filtro_custom (Mat img, int fator)"

.PP
Filtro de média\&. Aplicação do filtro de média de imagens\&.
.PP
\fBParameters:\fP
.RS 4
\fIimg\fP - Imagem a ser filtrada 
.br
\fIfator\fP - Dimensões do kernel quadrado a ser utilizado na filtragem 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
