.TH "/home/pedro/Dropbox/UnB2017-1/Introdução ao Processamento de Imagens/Projetos/Trabalhos/Trab1IPI/Ex1/src/trabalho.cc" 3 "Mon May 8 2017" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/pedro/Dropbox/UnB2017-1/Introdução ao Processamento de Imagens/Projetos/Trabalhos/Trab1IPI/Ex1/src/trabalho.cc \- Arquivo do primeiro exercício do primeiro trabalho de IPI UnB - 1/2017\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <dec_int\&.h>\fP
.br
\fC#include <edge_improv\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.RI "\fIMain do programa\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Arquivo do primeiro exercício do primeiro trabalho de IPI UnB - 1/2017\&. 


.PP
\fBAuthor:\fP
.RS 4
Pedro Nogueira - 14/0065032 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "int main ()"

.PP
Main do programa\&. Mostra imagens bonitinhas\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
