.TH "/home/pedro/Dropbox/UnB2017-1/Introdução ao Processamento de Imagens/Projetos/Trabalhos/Trab1IPI/src/trabalho.cc" 3 "Mon Apr 24 2017" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/pedro/Dropbox/UnB2017-1/Introdução ao Processamento de Imagens/Projetos/Trabalhos/Trab1IPI/src/trabalho.cc \- Arquivo que vai rodar opencv lindão\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <opencv2/opencv\&.hpp>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.RI "\fIMain do programa\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Arquivo que vai rodar opencv lindão\&. 


.PP
\fBAuthor:\fP
.RS 4
Pedro Nogueira - 14/0065032 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "int main ()"

.PP
Main do programa\&. Mostra imagens bonitinhas\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
